name: update RPM databases
on:
  push:
jobs:
  build-package:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            rpm:
            - 'open-source/P/proot/*.rpm'
            - '*/*.rpm'
            - '*.rpm'

      - name: Install required packages
        run: sudo apt-get install -yq createrepo-c

      - name: backend tests
        if: steps.filter.outputs.rpm == 'true'
        run: echo yes && createrepo_c --update --database --deltas ./open-source

      - name: Git Commit and Push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Update RPM repositories'
          name: updater-bot
          email: 96554164+cat-master21@users.noreply.github.com
          rebase: 'true'
