name: update RPM databases
on:
  push:
    branches: [ main ]
jobs:
  build-package:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Install required packages
        run: sudo apt-get install -yq createrepo-c

      - name: Update repositories
        run: |
          createrepo_c --update --database --zck --deltas ./open-source
          createrepo_c --update --database --zck --deltas ./proprietary
          git config --global user.email "96554164+cat-master21@users.noreply.github.com"
          git config --global user.name "cat-master21 (bot)"
          git commit -m "Update RPM repositories"
        
      - name: Git Commit and Push
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'main'
          commit-message: 'Update RPM repositories'
